// src/pages/ReportsPage.tsx
import { useState } from "react";
import { mockSales, mockProducts, getItemTotal, getProfit } from "@/lib/mock-data";
import { ArrowLeft, Calendar, TrendingUp, Package, Award } from "lucide-react";
import { useNavigate } from "react-router-dom";

type Period = 'today' | 'week' | 'month';

const ReportsPage = () => {
  const navigate = useNavigate();
  const [period, setPeriod] = useState<Period>('today');
  const now = new Date();
  const filteredSales = mockSales.filter(s => { if (s.status === 'refunded') return false; const d = new Date(s.date); if (period === 'today') return d.toDateString() === now.toDateString(); if (period === 'week') { const w = new Date(now); w.setDate(w.getDate() - 7); return d >= w; } const m = new Date(now); m.setMonth(m.getMonth() - 1); return d >= m; });
  const totalRevenue = filteredSales.reduce((s, sale) => s + sale.total, 0);
  const totalProfit = filteredSales.reduce((s, sale) => s + sale.items.reduce((is, item) => is + getProfit(item), 0), 0);
  const totalSales = filteredSales.length;
  const avgSale = totalSales > 0 ? totalRevenue / totalSales : 0;
  const productSales: Record<string, { name: string; qty: number; revenue: number; profit: number }> = {};
  filteredSales.forEach(sale => { sale.items.forEach(item => { const id = item.product.id; if (!productSales[id]) productSales[id] = { name: item.product.name, qty: 0, revenue: 0, profit: 0 }; productSales[id].qty += item.quantity; productSales[id].revenue += getItemTotal(item); productSales[id].profit += getProfit(item); }); });
  const topProducts = Object.values(productSales).sort((a, b) => b.revenue - a.revenue).slice(0, 5);
  const lowStock = mockProducts.filter(p => p.stock <= p.lowStockThreshold).sort((a, b) => a.stock / a.lowStockThreshold - b.stock / b.lowStockThreshold);
  const expiringProducts = mockProducts.filter(p => { if (!p.expiryDate) return false; const exp = new Date(p.expiryDate); const daysLeft = (exp.getTime() - now.getTime()) / (1000 * 60 * 60 * 24); return daysLeft <= 30 && daysLeft > 0; });
  const periodLabels: Record<Period, string> = { today: 'Danas', week: 'Ova nedelja', month: 'Ovaj mesec' };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3"><button onClick={() => navigate(-1)} className="p-1.5 text-muted-foreground"><ArrowLeft className="h-5 w-5" /></button><h1 className="text-xl font-bold text-foreground flex-1">Izveštaji</h1></div>
      <div className="flex gap-2">{(['today', 'week', 'month'] as Period[]).map(p => (<button key={p} onClick={() => setPeriod(p)} className={`flex-1 py-2 text-xs font-medium rounded-lg transition-colors ${period === p ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{periodLabels[p]}</button>))}</div>
      <div className="grid grid-cols-2 gap-3">
        <div className="bg-card border border-border rounded-xl p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wide">Prihod</p><p className="text-lg font-bold text-foreground">{totalRevenue.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">RSD</p></div>
        <div className="bg-card border border-border rounded-xl p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wide">Profit</p><p className="text-lg font-bold text-success">{totalProfit.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">RSD</p></div>
        <div className="bg-card border border-border rounded-xl p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wide">Br. prodaja</p><p className="text-lg font-bold text-foreground">{totalSales}</p></div>
        <div className="bg-card border border-border rounded-xl p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wide">Prosek račun</p><p className="text-lg font-bold text-foreground">{avgSale.toLocaleString('sr-RS', { maximumFractionDigits: 0 })}</p><p className="text-[10px] text-muted-foreground">RSD</p></div>
      </div>
      <div className="bg-card border border-border rounded-xl p-4 space-y-3">
        <h2 className="text-sm font-semibold text-foreground flex items-center gap-2"><Award className="h-4 w-4 text-primary" /> Najprodavaniji artikli</h2>
        {topProducts.length > 0 ? (<div className="space-y-2">{topProducts.map((p, i) => (<div key={i} className="flex items-center justify-between"><div className="flex items-center gap-2 min-w-0"><span className="text-xs font-bold text-muted-foreground w-5">{i + 1}.</span><div className="min-w-0"><p className="text-sm text-foreground truncate">{p.name}</p><p className="text-[10px] text-muted-foreground">{p.qty} prodato</p></div></div><div className="text-right shrink-0"><p className="text-sm font-medium text-foreground">{p.revenue.toLocaleString('sr-RS')} RSD</p><p className="text-[10px] text-success">+{p.profit.toLocaleString('sr-RS')} profit</p></div></div>))}</div>) : (<p className="text-sm text-muted-foreground text-center py-4">Nema prodaja u ovom periodu</p>)}
      </div>
      {lowStock.length > 0 && (<div className="bg-card border border-warning/20 rounded-xl p-4 space-y-2"><h2 className="text-sm font-semibold text-foreground flex items-center gap-2"><Package className="h-4 w-4 text-warning" /> Niske zalihe ({lowStock.length})</h2>{lowStock.slice(0, 5).map(p => (<div key={p.id} className="flex items-center justify-between text-xs"><span className="text-foreground">{p.name}</span><span className="text-destructive font-bold">{p.stock} / {p.lowStockThreshold}</span></div>))}</div>)}
      {expiringProducts.length > 0 && (<div className="bg-card border border-warning/20 rounded-xl p-4 space-y-2"><h2 className="text-sm font-semibold text-foreground flex items-center gap-2"><Calendar className="h-4 w-4 text-warning" /> Uskoro ističe rok ({expiringProducts.length})</h2>{expiringProducts.map(p => { const daysLeft = Math.ceil((new Date(p.expiryDate!).getTime() - now.getTime()) / (1000 * 60 * 60 * 24)); return (<div key={p.id} className="flex items-center justify-between text-xs"><span className="text-foreground">{p.name}</span><span className="text-warning font-bold">{daysLeft} dana</span></div>); })}</div>)}
    </div>
  );
};

export default ReportsPage;

// angular-app/src/app/pages/reports/reports-page.component.ts
import { Location } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { getItemTotal, getProfit, Product, Sale } from '../../shared/mock-data';
import {
  DashboardPeriod,
  MockStoreService,
} from '../../shared/mock-store.service';

interface ProductPerformance {
  id: string;
  name: string;
  qty: number;
  revenue: number;
  profit: number;
}

interface ExpiringProduct {
  product: Product;
  daysLeft: number;
}

@Component({
  selector: 'app-reports-page',
  standalone: true,
  templateUrl: './reports-page.component.html',
  styleUrl: './reports-page.component.css',
})
export class ReportsPageComponent {
  private readonly store = inject(MockStoreService);
  private readonly location = inject(Location);
  private readonly allProducts = this.store.products;
  private readonly salesByPeriod = this.store.salesByPeriod;

  protected readonly period = signal<DashboardPeriod>('today');
  protected readonly periodOptions: { key: DashboardPeriod; label: string }[] = [
    { key: 'today', label: 'Danas' },
    { key: 'week', label: 'Ova nedelja' },
    { key: 'month', label: 'Ovaj mesec' },
  ];

  protected readonly filteredSales = computed(() =>
    this.salesByPeriod()[this.period()],
  );

  protected readonly totals = computed(() => {
    const sales = this.filteredSales();
    const revenue = sales.reduce((sum, sale) => sum + sale.total, 0);
    const profit = sales.reduce(
      (sum, sale) =>
        sum + sale.items.reduce((itemSum, item) => itemSum + getProfit(item), 0),
      0,
    );
    const avgSale = sales.length ? revenue / sales.length : 0;

    return {
      revenue,
      profit,
      totalSales: sales.length,
      avgSale,
    };
  });

  protected readonly topProducts = computed<ProductPerformance[]>(() => {
    const performance: Record<string, ProductPerformance> = {};

    this.filteredSales().forEach((sale: Sale) => {
      sale.items.forEach((item) => {
        if (!performance[item.product.id]) {
          performance[item.product.id] = {
            id: item.product.id,
            name: item.product.name,
            qty: 0,
            revenue: 0,
            profit: 0,
          };
        }

        performance[item.product.id].qty += item.quantity;
        performance[item.product.id].revenue += getItemTotal(item);
        performance[item.product.id].profit += getProfit(item);
      });
    });

    return Object.values(performance)
      .sort((left, right) => right.revenue - left.revenue)
      .slice(0, 5);
  });

  protected readonly lowStock = computed(() =>
    this.store
      .lowStockProducts()
      .sort(
        (left, right) =>
          left.stock / left.lowStockThreshold - right.stock / right.lowStockThreshold,
      )
      .slice(0, 5),
  );

  protected readonly expiringProducts = computed<ExpiringProduct[]>(() => {
    const now = new Date().getTime();

    return this.allProducts()
      .filter((product) => !!product.expiryDate)
      .map((product) => ({
        product,
        daysLeft: Math.ceil(
          (new Date(product.expiryDate!).getTime() - now) /
            (1000 * 60 * 60 * 24),
        ),
      }))
      .filter((entry) => entry.daysLeft > 0 && entry.daysLeft <= 30)
      .sort((left, right) => left.daysLeft - right.daysLeft);
  });

  protected setPeriod(period: DashboardPeriod): void {
    this.period.set(period);
  }

  protected goBack(): void {
    this.location.back();
  }

  protected formatCurrency(value: number): string {
    return new Intl.NumberFormat('sr-RS').format(Math.round(value));
  }
}

<section class="app-page">
  <header class="reports-header">
    <button type="button" class="reports-header__back" (click)="goBack()" aria-label="Nazad">
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="m15 18-6-6 6-6" />
      </svg>
    </button>
    <h1>Izveštaji</h1>
  </header>

  <div class="reports-periods">
    @for (entry of periodOptions; track entry.key) {
      <button
        type="button"
        class="reports-periods__button"
        [class.reports-periods__button--active]="period() === entry.key"
        (click)="setPeriod(entry.key)"
      >
        {{ entry.label }}
      </button>
    }
  </div>

  <section class="reports-grid">
    <article class="metric-card app-card">
      <span class="metric-card__label">Prihod</span>
      <strong>{{ formatCurrency(totals().revenue) }}</strong>
      <span class="metric-card__suffix">RSD</span>
    </article>
    <article class="metric-card app-card">
      <span class="metric-card__label">Profit</span>
      <strong class="metric-card__value--success">{{ formatCurrency(totals().profit) }}</strong>
      <span class="metric-card__suffix">RSD</span>
    </article>
    <article class="metric-card app-card">
      <span class="metric-card__label">Br. prodaja</span>
      <strong>{{ totals().totalSales }}</strong>
      <span class="metric-card__suffix">&nbsp;</span>
    </article>
    <article class="metric-card app-card">
      <span class="metric-card__label">Prosečan račun</span>
      <strong>{{ formatCurrency(totals().avgSale) }}</strong>
      <span class="metric-card__suffix">RSD</span>
    </article>
  </section>

  <section class="report-panel app-card">
    <div class="report-panel__header">
      <h2>
        <svg viewBox="0 0 24 24" aria-hidden="true">
          <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6M18 9h1.5a2.5 2.5 0 0 0 0-5H18M4 22h16M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22M18 2H6v7a6 6 0 0 0 12 0V2Z" />
        </svg>
        Najprodavaniji artikli
      </h2>
    </div>
    @if (topProducts().length > 0) {
      <div class="report-list">
        @for (product of topProducts(); track product.id; let index = $index) {
          <article class="report-list__item">
            <div>
              <p class="report-list__title">{{ index + 1 }}. {{ product.name }}</p>
              <p class="report-list__meta">{{ product.qty }} prodato</p>
            </div>
            <div class="report-list__metrics">
              <strong>{{ formatCurrency(product.revenue) }} RSD</strong>
              <span>+{{ formatCurrency(product.profit) }} profit</span>
            </div>
          </article>
        }
      </div>
    } @else {
      <p class="app-muted">Nema prodaja u izabranom periodu.</p>
    }
  </section>

  @if (lowStock().length > 0) {
    <section class="report-panel report-panel--warning app-card">
      <div class="report-panel__header">
        <h2>
          <svg viewBox="0 0 24 24" aria-hidden="true" class="report-panel__icon--warning">
            <path d="M3 7.5 12 3l9 4.5-9 4.5L3 7.5Zm0 0V16.5L12 21l9-4.5V7.5" />
          </svg>
          Niske zalihe ({{ lowStock().length }})
        </h2>
      </div>
      <div class="report-list">
        @for (product of lowStock(); track product.id) {
          <article class="report-list__item report-list__item--compact">
            <span class="report-list__title">{{ product.name }}</span>
            <strong class="report-list__danger">{{ product.stock }} / {{ product.lowStockThreshold }}</strong>
          </article>
        }
      </div>
    </section>
  }

  @if (expiringProducts().length > 0) {
    <section class="report-panel report-panel--warning app-card">
      <div class="report-panel__header">
        <h2>
          <svg viewBox="0 0 24 24" aria-hidden="true" class="report-panel__icon--warning">
            <path d="M8 2v4M16 2v4M3 10h18M21 8H3V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8Z" />
          </svg>
          Uskoro ističe rok ({{ expiringProducts().length }})
        </h2>
      </div>
      <div class="report-list">
        @for (entry of expiringProducts(); track entry.product.id) {
          <article class="report-list__item report-list__item--compact">
            <span class="report-list__title">{{ entry.product.name }}</span>
            <strong class="report-list__warning">{{ entry.daysLeft }} dana</strong>
          </article>
        }
      </div>
    </section>
  }
</section>
