// angular-app/src/app/pages/customers/customers-page.component.ts
import { FormsModule } from '@angular/forms';
import { Component, computed, inject, signal } from '@angular/core';
import { Customer } from '../../shared/mock-data';
import { MockStoreService } from '../../shared/mock-store.service';

type DiscountType = 'percent' | 'fixed';

interface CustomerFormValue {
  name: string;
  phone: string;
  email: string;
  address: string;
  note: string;
}

const emptyCustomerForm: CustomerFormValue = {
  name: '',
  phone: '',
  email: '',
  address: '',
  note: '',
};

@Component({
  selector: 'app-customers-page',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './customers-page.component.html',
  styleUrl: './customers-page.component.css',
})
export class CustomersPageComponent {
  private readonly store = inject(MockStoreService);
  protected readonly customers = this.store.customers;
  private readonly customerStatsById = this.store.customerStatsById;
  private readonly saleItemsLabelById = this.store.saleItemsLabelById;

  protected readonly search = signal('');
  protected readonly showForm = signal(false);
  protected readonly editingId = signal<string | null>(null);
  protected readonly form = signal<CustomerFormValue>({ ...emptyCustomerForm });
  protected readonly discountValue = signal('');
  protected readonly discountType = signal<DiscountType>('percent');
  protected readonly selectedId = signal<string | null>(null);
  protected readonly pageMessage = signal<string | null>(null);

  protected readonly filteredCustomers = computed(() => {
    const query = this.search().trim().toLowerCase();
    const customers = this.customers();
    if (!query) {
      return customers;
    }

    return customers.filter(
      (customer) =>
        customer.name.toLowerCase().includes(query) ||
        customer.phone?.includes(query) ||
        customer.email?.toLowerCase().includes(query),
    );
  });

  protected readonly selectedCustomer = computed(() => {
    const id = this.selectedId();
    return id ? this.customers().find((customer) => customer.id === id) : undefined;
  });

  protected updateSearch(value: string): void {
    this.search.set(value);
  }

  protected openNew(): void {
    this.form.set({ ...emptyCustomerForm });
    this.discountValue.set('');
    this.discountType.set('percent');
    this.editingId.set(null);
    this.showForm.set(true);
    this.pageMessage.set(null);
  }

  protected openEdit(customer: Customer): void {
    this.form.set({
      name: customer.name,
      phone: customer.phone ?? '',
      email: customer.email ?? '',
      address: customer.address ?? '',
      note: customer.note ?? '',
    });
    this.discountValue.set(customer.defaultDiscount?.value?.toString() ?? '');
    this.discountType.set(customer.defaultDiscount?.type ?? 'percent');
    this.editingId.set(customer.id);
    this.showForm.set(true);
    this.pageMessage.set(null);
  }

  protected closeForm(): void {
    this.showForm.set(false);
    this.editingId.set(null);
  }

  protected updateForm<K extends keyof CustomerFormValue>(
    field: K,
    value: CustomerFormValue[K],
  ): void {
    this.form.update((current) => ({ ...current, [field]: value }));
  }

  protected toggleDiscountType(): void {
    this.discountType.set(this.discountType() === 'percent' ? 'fixed' : 'percent');
  }

  protected updateDiscountValue(value: string): void {
    this.discountValue.set(value);
  }

  protected async save(): Promise<void> {
    const form = this.form();
    if (!form.name.trim()) {
      this.pageMessage.set('Unesite ime kupca.');
      return;
    }

    const parsedDiscount = Number.parseFloat(this.discountValue().replace(',', '.'));
    const defaultDiscount =
      Number.isFinite(parsedDiscount) && parsedDiscount > 0
        ? { type: this.discountType(), value: parsedDiscount }
        : undefined;

    if (this.editingId()) {
      await this.store.updateCustomer({
        id: this.editingId()!,
        createdAt: this.store.getCustomerById(this.editingId()!)?.createdAt ?? new Date().toISOString(),
        ...form,
        defaultDiscount,
      });
      this.pageMessage.set('Kupac je ažuriran.');
    } else {
      await this.store.createCustomer({
        ...form,
        defaultDiscount,
      });
      this.pageMessage.set('Kupac dodat.');
    }

    this.closeForm();
  }

  protected async deleteCustomer(id: string): Promise<void> {
    const name = this.customers().find((c) => c.id === id)?.name ?? 'ovog kupca';
    if (!confirm(`Obrisati ${name}? Ova radnja se ne može poništiti.`)) return;
    await this.store.deleteCustomer(id);
    if (this.selectedId() === id) {
      this.selectedId.set(null);
    }
    this.pageMessage.set('Kupac je obrisan.');
  }

  protected toggleSelected(id: string): void {
    this.selectedId.set(this.selectedId() === id ? null : id);
  }

  protected clearSelected(): void {
    this.selectedId.set(null);
  }

  protected customerStats(customerId: string) {
    return this.customerStatsById()[customerId] ?? {
      salesCount: 0,
      totalSpent: 0,
      totalProfit: 0,
      sales: [],
    };
  }

  protected saleItemsSummary(_customerId: string, saleId: string): string {
    return this.saleItemsLabelById()[saleId] ?? '';
  }

  protected formatCurrency(value: number): string {
    return new Intl.NumberFormat('sr-RS').format(Math.round(value));
  }

  protected formatShortDate(value: string): string {
    return new Intl.DateTimeFormat('sr-RS', {
      day: '2-digit',
      month: '2-digit',
      year: '2-digit',
    }).format(new Date(value));
  }
}

<section class="app-page">
  <header class="entity-header">
    <h1>Kupci</h1>
    <button type="button" class="primary-button" (click)="openNew()">
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M12 5v14M5 12h14" />
      </svg>
      Novi
    </button>
  </header>

  @if (pageMessage()) {
    <section class="status-banner app-card">
      <strong>Status</strong>
      <span>{{ pageMessage() }}</span>
    </section>
  }

  <section class="search-card">
    <span class="search-card__icon">
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="m21 21-4.35-4.35M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15Z" />
      </svg>
    </span>
    <input
      type="text"
      [ngModel]="search()"
      (ngModelChange)="updateSearch($event)"
      placeholder="Pretraži po imenu, telefonu..."
    />
  </section>

  @if (showForm()) {
    <section class="entity-form app-card">
      <div class="entity-form__header">
        <h2>{{ editingId() ? 'Izmeni kupca' : 'Novi kupac' }}</h2>
        <button type="button" class="entity-close-btn" (click)="closeForm()">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
      <input type="text" [ngModel]="form().name" (ngModelChange)="updateForm('name', $event)" placeholder="Ime i prezime / Firma *" />
      <input type="text" [ngModel]="form().phone" (ngModelChange)="updateForm('phone', $event)" placeholder="Telefon" />
      <input type="text" [ngModel]="form().email" (ngModelChange)="updateForm('email', $event)" placeholder="Email" />
      <input type="text" [ngModel]="form().address" (ngModelChange)="updateForm('address', $event)" placeholder="Adresa" />
      <input type="text" [ngModel]="form().note" (ngModelChange)="updateForm('note', $event)" placeholder="Napomena" />
      <div class="entity-form__discount">
        <label class="app-muted">Podrazumevani popust</label>
        <div class="entity-form__discount-row">
          <button type="button" class="secondary-button" (click)="toggleDiscountType()">
            {{ discountType() === 'percent' ? '%' : 'RSD' }}
          </button>
          <input type="text" [ngModel]="discountValue()" (ngModelChange)="updateDiscountValue($event)" placeholder="0" />
          <span class="app-muted">na sve proizvode</span>
        </div>
      </div>
      <button type="button" class="primary-button" (click)="save()">
        {{ editingId() ? 'Sačuvaj izmene' : 'Dodaj kupca' }}
      </button>
    </section>
  }

  @if (selectedCustomer() && !showForm()) {
    <section class="entity-detail app-card">
      <div class="entity-detail__header">
        <h2>{{ selectedCustomer()!.name }}</h2>
        <button type="button" class="entity-close-btn" (click)="clearSelected()">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
      @if (selectedCustomer()!.phone) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.07 9.81 19.79 19.79 0 0 1 1 1.18 2 2 0 0 1 2.98 0h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.09 7.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 21 14.92Z" />
          </svg>
          {{ selectedCustomer()!.phone }}
        </p>
      }
      @if (selectedCustomer()!.email) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2Z" /><path d="m22 6-10 7L2 6" />
          </svg>
          {{ selectedCustomer()!.email }}
        </p>
      }
      @if (selectedCustomer()!.address) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0Z" /><circle cx="12" cy="10" r="3" />
          </svg>
          {{ selectedCustomer()!.address }}
        </p>
      }
      @if (selectedCustomer()!.defaultDiscount) {
        <p class="entity-detail__contact entity-detail__highlight">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M12 2 2 7l10 5 10-5-10-5ZM2 17l10 5 10-5M2 12l10 5 10-5" />
          </svg>
          Popust:
          {{ selectedCustomer()!.defaultDiscount!.type === 'percent'
            ? selectedCustomer()!.defaultDiscount!.value + '%'
            : formatCurrency(selectedCustomer()!.defaultDiscount!.value) + ' RSD' }}
        </p>
      }
      @if (selectedCustomer()!.note) { <p class="app-muted entity-detail__note">{{ selectedCustomer()!.note }}</p> }

      @let stats = customerStats(selectedCustomer()!.id);
      @if (stats.salesCount > 0) {
        <div class="entity-stats-header">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M3 3v18h18M7 16l4-4 4 4 4-4" />
          </svg>
          <span class="app-muted">Statistika</span>
        </div>
        <section class="entity-stats">
          <div><strong>{{ stats.salesCount }}</strong><span>Kupovina</span></div>
          <div><strong>{{ formatCurrency(stats.totalSpent) }}</strong><span>Potrošeno</span></div>
          <div><strong class="entity-stats__profit">{{ formatCurrency(stats.totalProfit) }}</strong><span>Profit</span></div>
        </section>
      } @else {
        <p class="app-muted">Nema kupovina.</p>
      }

      @if (stats.sales.length > 0) {
        <div class="entity-sales-header">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z" /><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" />
          </svg>
          <span class="app-muted">Istorija kupovina</span>
        </div>
        <div class="entity-sales">
          @for (sale of stats.sales; track sale.id) {
            <article class="entity-sales__item" [class.entity-sales__item--refunded]="sale.status === 'refunded'">
              <div class="entity-sales__top">
                <span>{{ formatShortDate(sale.date) }} @if (sale.status === 'refunded') { <span class="entity-sales__danger">STORNO</span> }</span>
                <strong>{{ formatCurrency(sale.total) }} RSD</strong>
              </div>
              <p class="app-muted">{{ saleItemsSummary(selectedCustomer()!.id, sale.id) }}</p>
            </article>
          }
        </div>
      }

      <div class="entity-actions">
        <button type="button" class="secondary-button entity-actions__btn" (click)="openEdit(selectedCustomer()!)">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5Z" />
          </svg>
          Izmeni
        </button>
        <button type="button" class="secondary-button entity-actions__btn entity-actions__danger-btn" (click)="deleteCustomer(selectedCustomer()!.id)">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6" />
          </svg>
          Obriši
        </button>
      </div>
    </section>
  }

  <div class="entity-list">
    @for (customer of filteredCustomers(); track customer.id) {
      <button type="button" class="entity-list__item app-card" (click)="toggleSelected(customer.id)">
        <div>
          <p class="entity-list__title">{{ customer.name }}</p>
          <p class="app-muted">
            {{ customer.phone || 'Bez telefona' }}
            @if (customer.defaultDiscount) {
              <span class="entity-list__warning">
                popust {{ customer.defaultDiscount.type === 'percent' ? customer.defaultDiscount.value + '%' : customer.defaultDiscount.value + ' RSD' }}
              </span>
            }
          </p>
        </div>
        <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-list__chevron-icon">
          <path d="m9 18 6-6-6-6" />
        </svg>
      </button>
    } @empty {
      <section class="empty-state">
        <strong>{{ search() ? 'Nema rezultata' : 'Nema kupaca' }}</strong>
      </section>
    }
  </div>
</section>

// src/pages/CustomersPage.tsx
import { useState } from "react";
import { mockCustomers, mockSales, Customer, getItemTotal, getProfit } from "@/lib/mock-data";
import { Users, Plus, Search, Phone, Mail, MapPin, Tag, Edit2, Trash2, X, ChevronRight, TrendingUp, Receipt } from "lucide-react";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

const emptyCustomer: Omit<Customer, 'id' | 'createdAt'> = { name: '', phone: '', email: '', address: '', note: '' };

const CustomersPage = () => {
  const [customers, setCustomers] = useState<Customer[]>(mockCustomers);
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<Customer, 'id' | 'createdAt'>>(emptyCustomer);
  const [discountValue, setDiscountValue] = useState("");
  const [discountType, setDiscountType] = useState<'percent' | 'fixed'>('percent');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = search.length >= 1 ? customers.filter(c => c.name.toLowerCase().includes(search.toLowerCase()) || c.phone?.includes(search) || c.email?.toLowerCase().includes(search.toLowerCase())) : customers;
  const openNew = () => { setForm(emptyCustomer); setDiscountValue(""); setDiscountType('percent'); setEditingId(null); setShowForm(true); };
  const openEdit = (c: Customer) => { setForm({ name: c.name, phone: c.phone || '', email: c.email || '', address: c.address || '', note: c.note || '', defaultDiscount: c.defaultDiscount }); setDiscountValue(c.defaultDiscount?.value?.toString() || ""); setDiscountType(c.defaultDiscount?.type || 'percent'); setEditingId(c.id); setShowForm(true); };
  const handleSave = () => { if (!form.name.trim()) { toast.error("Unesite ime kupca"); return; } const dv = parseFloat(discountValue.replace(',', '.')); const discount = !isNaN(dv) && dv > 0 ? { type: discountType, value: dv } : undefined; if (editingId) { setCustomers(prev => prev.map(c => c.id === editingId ? { ...c, ...form, defaultDiscount: discount } : c)); toast.success("Kupac ažuriran"); } else { setCustomers(prev => [{ id: `c${Date.now()}`, ...form, defaultDiscount: discount, createdAt: new Date().toISOString() }, ...prev]); toast.success("Kupac dodat"); } setShowForm(false); setEditingId(null); };
  const handleDelete = (id: string) => { setCustomers(prev => prev.filter(c => c.id !== id)); setSelectedId(null); toast.success("Kupac obrisan"); };
  const selected = selectedId ? customers.find(c => c.id === selectedId) : null;
  const getCustomerStats = (customerId: string) => { const customerSales = mockSales.filter(s => s.customerId === customerId && s.status === 'completed'); return { salesCount: customerSales.length, totalSpent: customerSales.reduce((sum, s) => sum + s.total, 0), totalProfit: customerSales.reduce((sum, s) => sum + s.items.reduce((is, item) => is + getProfit(item), 0), 0) }; };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between"><h1 className="text-xl font-bold text-foreground">Kupci</h1><button onClick={openNew} className="flex items-center gap-1.5 px-3 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium"><Plus className="h-4 w-4" /> Novi</button></div>
      <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input placeholder="Pretraži po imenu, telefonu..." value={search} onChange={e => setSearch(e.target.value)} className="pl-10 h-11 bg-card border-border" /></div>
      {showForm && (
        <div className="bg-card border border-primary/30 rounded-xl p-4 space-y-3">
          <div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-foreground">{editingId ? 'Izmeni kupca' : 'Novi kupac'}</h2><button onClick={() => setShowForm(false)} className="text-muted-foreground"><X className="h-4 w-4" /></button></div>
          <Input placeholder="Ime i prezime / Firma *" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="bg-background" />
          <Input placeholder="Telefon" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="bg-background" />
          <Input placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="bg-background" />
          <Input placeholder="Adresa" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} className="bg-background" />
          <Input placeholder="Napomena" value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} className="bg-background" />
          <div className="space-y-1.5"><label className="text-xs font-medium text-muted-foreground">Podrazumevani popust</label><div className="flex items-center gap-2"><button onClick={() => setDiscountType(discountType === 'percent' ? 'fixed' : 'percent')} className="px-3 py-2 text-xs font-mono bg-secondary rounded-lg border border-border">{discountType === 'percent' ? '%' : 'RSD'}</button><Input type="text" inputMode="decimal" placeholder="0" value={discountValue} onChange={e => setDiscountValue(e.target.value)} className="w-24 bg-background" /><span className="text-xs text-muted-foreground">na sve proizvode</span></div></div>
          <button onClick={handleSave} className="w-full py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium">{editingId ? 'Sačuvaj izmene' : 'Dodaj kupca'}</button>
        </div>
      )}
      {selected && !showForm && (
        <div className="bg-card border border-primary/30 rounded-xl p-4 space-y-3">
          <div className="flex items-center justify-between"><h2 className="text-base font-semibold text-foreground">{selected.name}</h2><button onClick={() => setSelectedId(null)} className="text-muted-foreground"><X className="h-4 w-4" /></button></div>
          {selected.phone && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Phone className="h-3.5 w-3.5" /> {selected.phone}</div>}
          {selected.email && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Mail className="h-3.5 w-3.5" /> {selected.email}</div>}
          {selected.address && <div className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5" /> {selected.address}</div>}
          {selected.defaultDiscount && <div className="flex items-center gap-2 text-sm text-warning"><Tag className="h-3.5 w-3.5" />Popust: {selected.defaultDiscount.type === 'percent' ? `${selected.defaultDiscount.value}%` : `${selected.defaultDiscount.value.toLocaleString('sr-RS')} RSD`}</div>}
          {selected.note && <p className="text-xs text-muted-foreground italic">{selected.note}</p>}
          {(() => { const stats = getCustomerStats(selected.id); const customerSales = mockSales.filter(s => s.customerId === selected.id); return (<div className="space-y-3">{stats.salesCount > 0 ? (<div className="bg-secondary/50 rounded-lg p-3 space-y-1.5"><p className="text-xs font-medium text-muted-foreground flex items-center gap-1"><TrendingUp className="h-3 w-3" /> Statistika</p><div className="grid grid-cols-3 gap-2 text-center"><div><p className="text-sm font-bold text-foreground">{stats.salesCount}</p><p className="text-[10px] text-muted-foreground">Kupovina</p></div><div><p className="text-sm font-bold text-foreground">{stats.totalSpent.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">Potrošeno</p></div><div><p className="text-sm font-bold text-success">{stats.totalProfit.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">Profit</p></div></div></div>) : <p className="text-xs text-muted-foreground text-center py-1">Nema kupovina</p>}{customerSales.length > 0 && (<div className="space-y-1.5"><p className="text-xs font-medium text-muted-foreground flex items-center gap-1"><Receipt className="h-3 w-3" /> Istorija kupovina</p><div className="space-y-1.5 max-h-48 overflow-y-auto">{customerSales.map(sale => (<div key={sale.id} className={`bg-background rounded-lg p-2.5 border ${sale.status === 'refunded' ? 'border-destructive/30 opacity-60' : 'border-border'}`}><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{new Date(sale.date).toLocaleDateString('sr-RS', { day: '2-digit', month: '2-digit', year: '2-digit' })}{sale.status === 'refunded' && <span className="ml-1 text-destructive font-medium">STORNO</span>}</span><span className="text-xs font-bold text-foreground">{sale.total.toLocaleString('sr-RS')} RSD</span></div><p className="text-[10px] text-muted-foreground truncate mt-0.5">{sale.items.map(i => `${i.product.name} ×${i.quantity}`).join(', ')}</p></div>))}</div></div>)}</div>); })()}
          <div className="flex gap-2"><button onClick={() => openEdit(selected)} className="flex-1 flex items-center justify-center gap-1.5 py-2 bg-secondary text-secondary-foreground rounded-lg text-xs font-medium"><Edit2 className="h-3.5 w-3.5" /> Izmeni</button><button onClick={() => handleDelete(selected.id)} className="flex items-center justify-center gap-1.5 px-4 py-2 bg-destructive/10 text-destructive rounded-lg text-xs font-medium"><Trash2 className="h-3.5 w-3.5" /> Obriši</button></div>
        </div>
      )}
      <div className="space-y-1.5">
        {filtered.map(c => (<button key={c.id} onClick={() => setSelectedId(c.id === selectedId ? null : c.id)} className={`w-full flex items-center justify-between bg-card border rounded-lg p-3 text-left transition-colors ${c.id === selectedId ? 'border-primary/40' : 'border-border hover:border-primary/20'}`}><div className="min-w-0 flex-1"><p className="text-sm font-medium text-foreground truncate">{c.name}</p><p className="text-xs text-muted-foreground">{c.phone || 'Bez telefona'}{c.defaultDiscount && <span className="ml-2 text-warning">popust {c.defaultDiscount.type === 'percent' ? `${c.defaultDiscount.value}%` : `${c.defaultDiscount.value} RSD`}</span>}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" /></button>))}
        {filtered.length === 0 && <div className="flex flex-col items-center py-8 text-muted-foreground"><Users className="h-8 w-8 mb-2 opacity-30" /><p className="text-sm">{search ? 'Nema rezultata' : 'Nema kupaca'}</p></div>}
      </div>
    </div>
  );
};

export default CustomersPage;
