// angular-app/src/app/pages/daily-close/daily-close-page.component.ts
import { FormsModule } from '@angular/forms';
import { Component, computed, inject, signal } from '@angular/core';
import { getItemTotal, getProfit } from '../../shared/mock-data';
import { MockStoreService } from '../../shared/mock-store.service';

interface SoldProductSummary {
  id: string;
  name: string;
  qty: number;
  revenue: number;
}

@Component({
  selector: 'app-daily-close-page',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './daily-close-page.component.html',
  styleUrl: './daily-close-page.component.css',
})
export class DailyClosePageComponent {
  private readonly store = inject(MockStoreService);
  private readonly sales = this.store.sales;

  protected readonly selectedDate = signal(
    new Date().toISOString().slice(0, 10),
  );

  protected readonly daySales = computed(() =>
    this.sales()
      .filter(
        (sale) => new Date(sale.date).toISOString().slice(0, 10) === this.selectedDate(),
      ),
  );

  protected readonly summary = computed(() => {
    const completed = this.daySales().filter((sale) => sale.status === 'completed');
    const refunded = this.daySales().filter((sale) => sale.status === 'refunded');
    const cashTotal = completed
      .filter((sale) => sale.paymentMethod === 'cash')
      .reduce((sum, sale) => sum + sale.total, 0);
    const cardTotal = completed
      .filter((sale) => sale.paymentMethod === 'card')
      .reduce((sum, sale) => sum + sale.total, 0);
    const totalRevenue = cashTotal + cardTotal;
    const totalProfit = completed.reduce(
      (sum, sale) =>
        sum + sale.items.reduce((itemSum, item) => itemSum + getProfit(item), 0),
      0,
    );
    const refundedTotal = refunded.reduce((sum, sale) => sum + sale.total, 0);
    const totalItems = completed.reduce(
      (sum, sale) =>
        sum + sale.items.reduce((itemSum, item) => itemSum + item.quantity, 0),
      0,
    );

    return {
      completed,
      refunded,
      cashTotal,
      cardTotal,
      totalRevenue,
      totalProfit,
      refundedTotal,
      totalItems,
      averageReceipt: completed.length ? totalRevenue / completed.length : 0,
    };
  });

  protected readonly soldProducts = computed<SoldProductSummary[]>(() => {
    const products: Record<string, SoldProductSummary> = {};

    this.summary().completed.forEach((sale) => {
      sale.items.forEach((item) => {
        if (!products[item.product.id]) {
          products[item.product.id] = {
            id: item.product.id,
            name: item.product.name,
            qty: 0,
            revenue: 0,
          };
        }

        products[item.product.id].qty += item.quantity;
        products[item.product.id].revenue += getItemTotal(item);
      });
    });

    return Object.values(products).sort((left, right) => right.revenue - left.revenue);
  });

  protected updateDate(value: string): void {
    this.selectedDate.set(value);
  }

  protected formatCurrency(value: number): string {
    return new Intl.NumberFormat('sr-RS').format(Math.round(value));
  }

  protected formatLongDate(value: string): string {
    return new Intl.DateTimeFormat('sr-RS', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    }).format(new Date(value));
  }

  protected print(): void {
    window.print();
  }
}

<section class="app-page">
  <header class="daily-close-header">
    <h1>Z-izveštaj</h1>
    <button type="button" class="secondary-button" (click)="print()">Štampaj</button>
  </header>

  <input
    class="daily-close-date"
    type="date"
    [ngModel]="selectedDate()"
    (ngModelChange)="updateDate($event)"
  />

  <section class="daily-close-summary app-card">
    <h2>Dnevni zaključak - {{ formatLongDate(selectedDate()) }}</h2>

    <div class="daily-close-metrics">
      <article class="metric-card">
        <svg viewBox="0 0 24 24" aria-hidden="true" class="metric-card__icon metric-card__icon--success">
          <path d="M2 9h20v11a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V9ZM2 9V7a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v2M12 15a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
        </svg>
        <span>Gotovina</span>
        <strong>{{ formatCurrency(summary().cashTotal) }}</strong>
        <small>RSD</small>
      </article>
      <article class="metric-card">
        <svg viewBox="0 0 24 24" aria-hidden="true" class="metric-card__icon metric-card__icon--primary">
          <path d="M2 8h20M2 12h4M6 16h4M2 5h20a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z" />
        </svg>
        <span>Kartica</span>
        <strong>{{ formatCurrency(summary().cardTotal) }}</strong>
        <small>RSD</small>
      </article>
    </div>

    <div class="daily-close-details">
      <div>
        <span class="daily-close-details__label">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="daily-close-details__icon">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z" /><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" />
          </svg>
          Ukupan pazar
        </span>
        <strong>{{ formatCurrency(summary().totalRevenue) }} RSD</strong>
      </div>
      <div>
        <span class="daily-close-details__label">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="daily-close-details__icon">
            <path d="M3 3v18h18M7 16l4-4 4 4 4-4" />
          </svg>
          Zarada
        </span>
        <strong class="metric-card__positive">{{ formatCurrency(summary().totalProfit) }} RSD</strong>
      </div>
      <div>
        <span class="daily-close-details__label">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="daily-close-details__icon">
            <path d="M3 7.5 12 3l9 4.5-9 4.5L3 7.5Zm0 0V16.5L12 21l9-4.5V7.5" />
          </svg>
          Prodatih artikala
        </span>
        <strong>{{ summary().totalItems }}</strong>
      </div>
      <div><span>Broj računa</span><strong>{{ summary().completed.length }}</strong></div>
      <div><span>Prosečan račun</span><strong>{{ formatCurrency(summary().averageReceipt) }} RSD</strong></div>
      @if (summary().refunded.length > 0) {
        <div><span class="metric-card__negative">Stornirano ({{ summary().refunded.length }})</span><strong class="metric-card__negative">-{{ formatCurrency(summary().refundedTotal) }} RSD</strong></div>
      }
    </div>
  </section>

  @if (soldProducts().length > 0) {
    <section class="daily-close-list app-card">
      <h2>Prodati artikli</h2>
      <div class="daily-close-list__rows">
        @for (product of soldProducts(); track product.id) {
          <div class="daily-close-list__row">
            <div>
              <p>{{ product.name }}</p>
              <span class="app-muted">{{ product.qty }} kom</span>
            </div>
            <strong>{{ formatCurrency(product.revenue) }} RSD</strong>
          </div>
        }
      </div>
    </section>
  }

  @if (summary().completed.length === 0) {
    <section class="app-card empty-state">
      <strong>Nema prodaja za ovaj dan</strong>
      <span class="app-muted">Izaberite drugi datum ili prvo evidentirajte prodaje kroz migrirane rute.</span>
    </section>
  }
</section>

// src/pages/DailyClosePage.tsx
import { useState } from "react";
import { ArrowLeft, Printer, Banknote, CreditCard, Receipt, TrendingUp, Package } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { mockSales, getProfit, getItemTotal } from "@/lib/mock-data";

const DailyClosePage = () => {
  const navigate = useNavigate();
  const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().slice(0, 10));
  const daySales = mockSales.filter(s => new Date(s.date).toISOString().slice(0, 10) === selectedDate);
  const completed = daySales.filter(s => s.status === 'completed');
  const refunded = daySales.filter(s => s.status === 'refunded');
  const cashTotal = completed.filter(s => s.paymentMethod === 'cash').reduce((sum, s) => sum + s.total, 0);
  const cardTotal = completed.filter(s => s.paymentMethod === 'card').reduce((sum, s) => sum + s.total, 0);
  const totalRevenue = cashTotal + cardTotal;
  const totalProfit = completed.reduce((sum, s) => sum + s.items.reduce((is, item) => is + getProfit(item), 0), 0);
  const refundedTotal = refunded.reduce((sum, s) => sum + s.total, 0);
  const totalItems = completed.reduce((sum, s) => sum + s.items.reduce((is, i) => is + i.quantity, 0), 0);
  const productMap: Record<string, { name: string; qty: number; revenue: number }> = {};
  completed.forEach(sale => { sale.items.forEach(item => { const id = item.product.id; if (!productMap[id]) productMap[id] = { name: item.product.name, qty: 0, revenue: 0 }; productMap[id].qty += item.quantity; productMap[id].revenue += getItemTotal(item); }); });
  const productList = Object.values(productMap).sort((a, b) => b.revenue - a.revenue);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3"><button onClick={() => navigate(-1)} className="p-1.5 text-muted-foreground"><ArrowLeft className="h-5 w-5" /></button><h1 className="text-xl font-bold text-foreground flex-1">Z-Izveštaj</h1><button onClick={() => window.print()} className="p-2 text-primary"><Printer className="h-5 w-5" /></button></div>
      <input type="date" value={selectedDate} onChange={e => setSelectedDate(e.target.value)} className="w-full h-10 px-3 text-sm bg-secondary border border-border rounded-lg text-foreground" />
      <div className="bg-card border border-border rounded-xl p-4 space-y-4">
        <h2 className="text-sm font-semibold text-foreground text-center">Dnevni zaključak — {new Date(selectedDate).toLocaleDateString('sr-RS', { day: '2-digit', month: 'long', year: 'numeric' })}</h2>
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-secondary/50 rounded-lg p-3 text-center"><Banknote className="h-5 w-5 text-success mx-auto mb-1" /><p className="text-[10px] text-muted-foreground uppercase">Gotovina</p><p className="text-lg font-bold text-foreground">{cashTotal.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">RSD</p></div>
          <div className="bg-secondary/50 rounded-lg p-3 text-center"><CreditCard className="h-5 w-5 text-primary mx-auto mb-1" /><p className="text-[10px] text-muted-foreground uppercase">Kartica</p><p className="text-lg font-bold text-foreground">{cardTotal.toLocaleString('sr-RS')}</p><p className="text-[10px] text-muted-foreground">RSD</p></div>
        </div>
        <div className="border-t border-border pt-3 space-y-2">
          <div className="flex justify-between text-sm"><span className="text-muted-foreground flex items-center gap-1.5"><Receipt className="h-4 w-4" /> Ukupan pazar</span><span className="font-bold text-foreground">{totalRevenue.toLocaleString('sr-RS')} RSD</span></div>
          <div className="flex justify-between text-sm"><span className="text-muted-foreground flex items-center gap-1.5"><TrendingUp className="h-4 w-4" /> Zarada</span><span className="font-bold text-success">{totalProfit.toLocaleString('sr-RS')} RSD</span></div>
          <div className="flex justify-between text-sm"><span className="text-muted-foreground flex items-center gap-1.5"><Package className="h-4 w-4" /> Prodatih artikala</span><span className="font-bold text-foreground">{totalItems}</span></div>
          <div className="flex justify-between text-sm"><span className="text-muted-foreground">Broj računa</span><span className="font-bold text-foreground">{completed.length}</span></div>
          <div className="flex justify-between text-sm"><span className="text-muted-foreground">Prosek račun</span><span className="font-bold text-foreground">{completed.length > 0 ? Math.round(totalRevenue / completed.length).toLocaleString('sr-RS') : 0} RSD</span></div>
          {refunded.length > 0 && <div className="flex justify-between text-sm"><span className="text-destructive">Stornirano ({refunded.length})</span><span className="font-bold text-destructive">-{refundedTotal.toLocaleString('sr-RS')} RSD</span></div>}
        </div>
      </div>
      {productList.length > 0 && (<div className="bg-card border border-border rounded-xl p-4 space-y-2"><h2 className="text-sm font-semibold text-foreground">Prodati artikli</h2>{productList.map((p, i) => (<div key={i} className="flex items-center justify-between text-xs py-1.5 border-b border-border last:border-0"><div className="min-w-0 flex-1"><p className="text-foreground truncate">{p.name}</p><p className="text-muted-foreground">{p.qty} kom</p></div><span className="font-mono font-medium text-foreground shrink-0 ml-2">{p.revenue.toLocaleString('sr-RS')} RSD</span></div>))}</div>)}
      {completed.length === 0 && <div className="text-center py-12 text-muted-foreground"><Receipt className="h-12 w-12 mx-auto mb-3 opacity-30" /><p className="text-sm">Nema prodaja za ovaj dan</p></div>}
    </div>
  );
};

export default DailyClosePage;
