// angular-app/src/app/pages/suppliers/suppliers-page.component.ts
import { FormsModule } from '@angular/forms';
import { Component, computed, inject, signal } from '@angular/core';
import { Supplier } from '../../shared/mock-data';
import { MockStoreService } from '../../shared/mock-store.service';
import { SnackbarService } from '../../shared/snackbar.service';

interface SupplierFormValue {
  name: string;
  phone: string;
  email: string;
  address: string;
  note: string;
  products: string;
}

const emptySupplierForm: SupplierFormValue = {
  name: '',
  phone: '',
  email: '',
  address: '',
  note: '',
  products: '',
};

@Component({
  selector: 'app-suppliers-page',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './suppliers-page.component.html',
  styleUrl: './suppliers-page.component.css',
})
export class SuppliersPageComponent {
  private readonly store = inject(MockStoreService);
  private readonly snackbar = inject(SnackbarService);
  protected readonly suppliers = this.store.suppliers;

  protected readonly search = signal('');
  protected readonly showForm = signal(false);
  protected readonly editingId = signal<string | null>(null);
  protected readonly form = signal<SupplierFormValue>({ ...emptySupplierForm });
  protected readonly selectedId = signal<string | null>(null);

  protected readonly filteredSuppliers = computed(() => {
    const query = this.search().trim().toLowerCase();
    const suppliers = this.suppliers();
    if (!query) {
      return suppliers;
    }

    return suppliers.filter(
      (supplier) =>
        supplier.name.toLowerCase().includes(query) ||
        supplier.phone?.includes(query),
    );
  });

  protected readonly selectedSupplier = computed(() => {
    const id = this.selectedId();
    return id ? this.suppliers().find((supplier) => supplier.id === id) : undefined;
  });

  protected updateSearch(value: string): void {
    this.search.set(value);
  }

  protected openNew(): void {
    this.form.set({ ...emptySupplierForm });
    this.editingId.set(null);
    this.showForm.set(true);
  }

  protected openEdit(supplier: Supplier): void {
    this.form.set({
      name: supplier.name,
      phone: supplier.phone ?? '',
      email: supplier.email ?? '',
      address: supplier.address ?? '',
      note: supplier.note ?? '',
      products: supplier.products?.join(', ') ?? '',
    });
    this.editingId.set(supplier.id);
    this.showForm.set(true);
  }

  protected closeForm(): void {
    this.showForm.set(false);
    this.editingId.set(null);
  }

  protected updateForm<K extends keyof SupplierFormValue>(
    field: K,
    value: SupplierFormValue[K],
  ): void {
    this.form.update((current) => ({ ...current, [field]: value }));
  }

  protected async save(): Promise<void> {
    const form = this.form();
    if (!form.name.trim()) {
      this.snackbar.error('Unesite ime dobavljača.');
      return;
    }

    const products = form.products
      .split(',')
      .map((value) => value.trim())
      .filter(Boolean);

    if (this.editingId()) {
      await this.store.updateSupplier({
        id: this.editingId()!,
        createdAt: this.store.getSupplierById(this.editingId()!)?.createdAt ?? new Date().toISOString(),
        name: form.name,
        phone: form.phone || undefined,
        email: form.email || undefined,
        address: form.address || undefined,
        note: form.note || undefined,
        products,
      });
      this.snackbar.success('Dobavljač je ažuriran.');
    } else {
      await this.store.createSupplier({
        name: form.name,
        phone: form.phone || undefined,
        email: form.email || undefined,
        address: form.address || undefined,
        note: form.note || undefined,
        products,
      });
      this.snackbar.success('Dobavljač je dodat.');
    }

    this.closeForm();
  }

  protected async deleteSupplier(id: string): Promise<void> {
    const name = this.suppliers().find((s) => s.id === id)?.name ?? 'ovog dobavljača';
    if (!confirm(`Obrisati ${name}? Ova radnja se ne može poništiti.`)) return;
    await this.store.deleteSupplier(id);
    if (this.selectedId() === id) {
      this.selectedId.set(null);
    }
    this.snackbar.success('Dobavljač je obrisan.');
  }

  protected toggleSelected(id: string): void {
    this.selectedId.set(this.selectedId() === id ? null : id);
  }

  protected clearSelected(): void {
    this.selectedId.set(null);
  }
}

<section class="app-page">
  <header class="entity-header">
    <h1>Dobavljači</h1>
    <button type="button" class="primary-button" (click)="openNew()">
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M12 5v14M5 12h14" />
      </svg>
      Novi
    </button>
  </header>

  <section class="search-card">
    <span class="search-card__icon">
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="m21 21-4.35-4.35M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15Z" />
      </svg>
    </span>
    <input
      type="text"
      [ngModel]="search()"
      (ngModelChange)="updateSearch($event)"
      placeholder="Pretraži po imenu, telefonu..."
    />
  </section>

  @if (showForm()) {
    <section class="entity-form app-card">
      <div class="entity-form__header">
        <h2>{{ editingId() ? 'Izmeni dobavljača' : 'Novi dobavljač' }}</h2>
        <button type="button" class="entity-close-btn" (click)="closeForm()">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
      <input type="text" [ngModel]="form().name" (ngModelChange)="updateForm('name', $event)" placeholder="Naziv firme / Ime *" />
      <input type="text" [ngModel]="form().phone" (ngModelChange)="updateForm('phone', $event)" placeholder="Telefon" />
      <input type="text" [ngModel]="form().email" (ngModelChange)="updateForm('email', $event)" placeholder="Email" />
      <input type="text" [ngModel]="form().address" (ngModelChange)="updateForm('address', $event)" placeholder="Adresa" />
      <input type="text" [ngModel]="form().note" (ngModelChange)="updateForm('note', $event)" placeholder="Napomena" />
      <input type="text" [ngModel]="form().products" (ngModelChange)="updateForm('products', $event)" placeholder="Proizvodi, odvojeni zarezom" />
      <button type="button" class="primary-button" (click)="save()">
        {{ editingId() ? 'Sačuvaj izmene' : 'Dodaj dobavljača' }}
      </button>
    </section>
  }

  @if (selectedSupplier() && !showForm()) {
    <section class="entity-detail app-card">
      <div class="entity-detail__header">
        <h2>{{ selectedSupplier()!.name }}</h2>
        <button type="button" class="entity-close-btn" (click)="clearSelected()">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
      @if (selectedSupplier()!.phone) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.07 9.81 19.79 19.79 0 0 1 1 1.18 2 2 0 0 1 2.98 0h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.09 7.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 21 14.92Z" />
          </svg>
          {{ selectedSupplier()!.phone }}
        </p>
      }
      @if (selectedSupplier()!.email) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2Z" /><path d="m22 6-10 7L2 6" />
          </svg>
          {{ selectedSupplier()!.email }}
        </p>
      }
      @if (selectedSupplier()!.address) {
        <p class="entity-detail__contact">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0Z" /><circle cx="12" cy="10" r="3" />
          </svg>
          {{ selectedSupplier()!.address }}
        </p>
      }
      @if (selectedSupplier()!.products && selectedSupplier()!.products!.length > 0) {
        <div class="supplier-products">
          <p class="supplier-products__label">
            <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-detail__contact-icon">
              <path d="M3 7.5 12 3l9 4.5-9 4.5L3 7.5Zm0 0V16.5L12 21l9-4.5V7.5" />
            </svg>
            Proizvodi ({{ selectedSupplier()!.products!.length }})
          </p>
          <div class="supplier-products__list">
            @for (product of selectedSupplier()!.products!; track product) {
              <span class="app-badge">{{ product }}</span>
            }
          </div>
        </div>
      }
      @if (selectedSupplier()!.note) { <p class="app-muted entity-detail__note">{{ selectedSupplier()!.note }}</p> }

      <div class="entity-actions">
        <button type="button" class="secondary-button entity-actions__btn" (click)="openEdit(selectedSupplier()!)">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5Z" />
          </svg>
          Izmeni
        </button>
        <button type="button" class="secondary-button entity-actions__btn entity-actions__danger-btn" (click)="deleteSupplier(selectedSupplier()!.id)">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6" />
          </svg>
          Obriši
        </button>
      </div>
    </section>
  }

  <div class="entity-list">
    @for (supplier of filteredSuppliers(); track supplier.id) {
      <button type="button" class="entity-list__item app-card" (click)="toggleSelected(supplier.id)">
        <div>
          <p class="entity-list__title">{{ supplier.name }}</p>
          <p class="app-muted">{{ supplier.phone || 'Bez telefona' }}</p>
        </div>
        <svg viewBox="0 0 24 24" aria-hidden="true" class="entity-list__chevron-icon">
          <path d="m9 18 6-6-6-6" />
        </svg>
      </button>
    } @empty {
      <section class="empty-state">
        <strong>{{ search() ? 'Nema rezultata' : 'Nema dobavljača' }}</strong>
      </section>
    }
  </div>
</section>

// src/pages/SuppliersPage.tsx
import { useState } from "react";
import { mockSuppliers, Supplier } from "@/lib/mock-data";
import { Truck, Plus, Search, Phone, Mail, MapPin, Edit2, Trash2, X, ChevronRight, Package } from "lucide-react";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";

const emptySupplier: Omit<Supplier, 'id' | 'createdAt'> = { name: '', phone: '', email: '', address: '', note: '', products: [] };

const SuppliersPage = () => {
  const navigate = useNavigate();
  const [suppliers, setSuppliers] = useState<Supplier[]>(mockSuppliers);
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<Supplier, 'id' | 'createdAt'>>(emptySupplier);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const filtered = search.length >= 1 ? suppliers.filter(s => s.name.toLowerCase().includes(search.toLowerCase()) || s.phone?.includes(search)) : suppliers;
  const openNew = () => { setForm(emptySupplier); setEditingId(null); setShowForm(true); };
  const openEdit = (s: Supplier) => { setForm({ name: s.name, phone: s.phone || '', email: s.email || '', address: s.address || '', note: s.note || '', products: s.products || [] }); setEditingId(s.id); setShowForm(true); };
  const handleSave = () => { if (!form.name.trim()) { toast.error("Unesite ime dobavljača"); return; } if (editingId) { setSuppliers(prev => prev.map(s => s.id === editingId ? { ...s, ...form } : s)); toast.success("Dobavljač ažuriran"); } else { setSuppliers(prev => [{ id: `sup${Date.now()}`, ...form, createdAt: new Date().toISOString() }, ...prev]); toast.success("Dobavljač dodat"); } setShowForm(false); setEditingId(null); };
  const handleDelete = (id: string) => { setSuppliers(prev => prev.filter(s => s.id !== id)); setSelectedId(null); toast.success("Dobavljač obrisan"); };
  const selected = selectedId ? suppliers.find(s => s.id === selectedId) : null;

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between"><h1 className="text-xl font-bold text-foreground">Dobavljači</h1><button onClick={openNew} className="flex items-center gap-1.5 px-3 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium"><Plus className="h-4 w-4" /> Novi</button></div>
      <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input placeholder="Pretraži po imenu, telefonu..." value={search} onChange={e => setSearch(e.target.value)} className="pl-10 h-11 bg-card border-border" /></div>
      {showForm && (<div className="bg-card border border-primary/30 rounded-xl p-4 space-y-3"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-foreground">{editingId ? 'Izmeni dobavljača' : 'Novi dobavljač'}</h2><button onClick={() => setShowForm(false)} className="text-muted-foreground"><X className="h-4 w-4" /></button></div><Input placeholder="Naziv firme / Ime *" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="bg-background" /><Input placeholder="Telefon" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="bg-background" /><Input placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="bg-background" /><Input placeholder="Adresa" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} className="bg-background" /><Input placeholder="Napomena" value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} className="bg-background" /><button onClick={handleSave} className="w-full py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium">{editingId ? 'Sačuvaj izmene' : 'Dodaj dobavljača'}</button></div>)}
      {selected && !showForm && (<div className="bg-card border border-primary/30 rounded-xl p-4 space-y-3"><div className="flex items-center justify-between"><h2 className="text-base font-semibold text-foreground">{selected.name}</h2><button onClick={() => setSelectedId(null)} className="text-muted-foreground"><X className="h-4 w-4" /></button></div>{selected.phone && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Phone className="h-3.5 w-3.5" /> {selected.phone}</div>}{selected.email && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Mail className="h-3.5 w-3.5" /> {selected.email}</div>}{selected.address && <div className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5" /> {selected.address}</div>}{selected.products && selected.products.length > 0 && <div className="space-y-1"><p className="text-xs font-medium text-muted-foreground flex items-center gap-1"><Package className="h-3 w-3" /> Proizvodi ({selected.products.length})</p><div className="flex flex-wrap gap-1">{selected.products.map(pid => <span key={pid} className="text-[10px] bg-secondary px-2 py-0.5 rounded-full text-foreground">{pid}</span>)}</div></div>}{selected.note && <p className="text-xs text-muted-foreground italic">{selected.note}</p>}<div className="flex gap-2"><button onClick={() => openEdit(selected)} className="flex-1 flex items-center justify-center gap-1.5 py-2 bg-secondary text-secondary-foreground rounded-lg text-xs font-medium"><Edit2 className="h-3.5 w-3.5" /> Izmeni</button><button onClick={() => handleDelete(selected.id)} className="flex items-center justify-center gap-1.5 px-4 py-2 bg-destructive/10 text-destructive rounded-lg text-xs font-medium"><Trash2 className="h-3.5 w-3.5" /> Obriši</button></div></div>)}
      <div className="space-y-1.5">{filtered.map(s => (<button key={s.id} onClick={() => setSelectedId(s.id === selectedId ? null : s.id)} className={`w-full flex items-center justify-between bg-card border rounded-lg p-3 text-left transition-colors ${s.id === selectedId ? 'border-primary/40' : 'border-border hover:border-primary/20'}`}><div className="min-w-0 flex-1"><p className="text-sm font-medium text-foreground truncate">{s.name}</p><p className="text-xs text-muted-foreground">{s.phone || 'Bez telefona'}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" /></button>))}{filtered.length === 0 && <div className="flex flex-col items-center py-8 text-muted-foreground"><Truck className="h-8 w-8 mb-2 opacity-30" /><p className="text-sm">{search ? 'Nema rezultata' : 'Nema dobavljača'}</p></div>}</div>
    </div>
  );
};

export default SuppliersPage;
